# Made by Mister 💛
from dataclasses import dataclass, field
from typing import List, Dict

@dataclass
class TemplateMessage:
    role: str  # e.g. 'Analyst', 'Buyer', 'Skeptic'
    text: str
    is_media: bool = False

@dataclass
class ConversationTemplate:
    name: str
    sentiment: str
    script: List[TemplateMessage] = field(default_factory=list)

class NewsTemplates:
    """The 'Scripts' (core/models/). Pre-defined conversation flows for 80-msg simulations."""

    # Archetype: BULLISH (80 msgs)
    BULL_RUN = ConversationTemplate(
        name="Bullish High-Growth",
        sentiment="bullish",
        script=[
            TemplateMessage("A", "{greeting}! Did you see [ASSET] news?"),
            TemplateMessage("B", "{agreement}, {sentiment_pos}!"),
            TemplateMessage("C", "Just checked my balance. [BALANCE]"),
            TemplateMessage("D", "{earnings_vibe} [BALANCE] Profits hitting."),
            TemplateMessage("A", "{ai_praise}. It's getting serious."),
            TemplateMessage("B", "{joke}. AI is literally printing."),
            TemplateMessage("E", "Just topped up more funds. [DEPOSIT]"),
            TemplateMessage("C", "Is it too late to enter?"),
            TemplateMessage("D", "Never too late with this AI logic."),
            TemplateMessage("F", "{interjection} Look at this trade result! [PROFIT]"),
            TemplateMessage("A", "{noun_market} is showing {adverb_speed} {action}."),
            TemplateMessage("B", "{filler}, wait for the breakout."),
            TemplateMessage("C", "AI just sent another alert. {earnings_vibe}"),
            TemplateMessage("E", "Withdrew my initial investment. [WITHDRAWAL]"),
            TemplateMessage("F", "Risk free now! [BALANCE] Check it out."),
            TemplateMessage("D", "Look at the chart! [ASSET] {verb_move} {adverb_speed}."),
            TemplateMessage("B", "I'm adding on the dip. [DEPOSIT]"),
            TemplateMessage("A", "{ai_praise}! Manual trading is dead."),
            TemplateMessage("C", "Just shared my progress [BALANCE]"),
            TemplateMessage("E", "{joke}. Getting paid while sleeping."),
            TemplateMessage("A", "{interjection}! {profit_expression}"),
            TemplateMessage("B", "My {noun_market} view is {sentiment_pos}."),
            TemplateMessage("C", "Anyone else in [ASSET] long?"),
            TemplateMessage("D", "AI took me long at the bottom. [BALANCE]"),
            TemplateMessage("E", "{ai_praise}. Best decision ever."),
            TemplateMessage("F", "Another win. [PROFIT] {earnings_vibe}"),
            TemplateMessage("G", "{greeting} familia! {market_vibe}"),
            TemplateMessage("H", "Wait, [ASSET] is pushing again!"),
            TemplateMessage("A", "{filler}. Let it run."),
            TemplateMessage("B", "{profit_expression}. AI is life."),
            TemplateMessage("C", "[BALANCE] hitting targets."),
            TemplateMessage("D", "Sharing is caring [PROFIT]"),
            TemplateMessage("E", "{joke}. Banks are crying."),
            TemplateMessage("F", "{interjection}! [ASSET] {verb_move} {adverb_speed}."),
            TemplateMessage("G", "{ai_praise}. Quant power."),
            TemplateMessage("H", "Just added [DEPOSIT]. Ready for more."),
            TemplateMessage("A", "{market_vibe} {earnings_vibe}"),
            TemplateMessage("B", "Anyone taking [WITHDRAWAL]?"),
            TemplateMessage("C", "Not yet, compounding [BALANCE]."),
            TemplateMessage("D", "{joke}. The dev is a legend."),
            TemplateMessage("E", "{ai_praise}. Automation is King."),
            TemplateMessage("F", "Watch the {noun_market} wick!"),
            TemplateMessage("G", "{agreement}. Speed is {adverb_speed}."),
            TemplateMessage("H", "[PROFIT] keeps growing."),
            TemplateMessage("A", "{greeting} legends! {market_vibe}"),
            TemplateMessage("B", "{profit_expression}. Just in time."),
            TemplateMessage("C", "Look at [BALANCE] now!"),
            TemplateMessage("D", "{interjection}! AI is a machine."),
            TemplateMessage("E", "Never seen [ASSET] move like this."),
            TemplateMessage("F", "{ai_praise}. Consistent gains."),
            TemplateMessage("G", "[DEPOSIT] sent. No FOMO, just logic."),
            TemplateMessage("H", "{joke}. Retire at 30? Done."),
            TemplateMessage("A", "{earnings_vibe} [PROFIT]"),
            TemplateMessage("B", "{filler}. Market is {sentiment_pos}."),
            TemplateMessage("C", "I'm withdrawing half. [WITHDRAWAL]"),
            TemplateMessage("D", "{ai_praise}. Safer than a bank."),
            TemplateMessage("E", "{market_vibe} {interjection}"),
            TemplateMessage("F", "Check [BALANCE] fam."),
            TemplateMessage("G", "Who is the dev? Mister is a god!"),
            TemplateMessage("H", "{ai_praise}. Best group ever."),
            TemplateMessage("A", "AI just adjusted risk. [BALANCE]"),
            TemplateMessage("B", "{profit_expression}"),
            TemplateMessage("C", "[ASSET] {verb_move} towards moon."),
            TemplateMessage("D", "Just got paid! [PROFIT]"),
            TemplateMessage("E", "{joke}. Manual guys rekt."),
            TemplateMessage("F", "{agreement}. {noun_market} is simple now."),
            TemplateMessage("G", "{earnings_vibe} [DEPOSIT]"),
            TemplateMessage("H", "Ready for the next cycle."),
            TemplateMessage("A", "{ai_praise}. Quant engine logic."),
            TemplateMessage("B", "{market_vibe} {filler}"),
            TemplateMessage("C", "[WITHDRAWAL] for the weekend."),
            TemplateMessage("D", "{interjection}! [BALANCE]"),
            TemplateMessage("E", "Is the bot still open for news?"),
            TemplateMessage("F", "Yes, just keep it on Lazy Mode."),
            TemplateMessage("G", "{ai_praise}. Automation wins."),
            TemplateMessage("H", "Look at [ASSET] now! {verb_move}"),
            TemplateMessage("A", "{joke}. I'm chilling."),
            TemplateMessage("B", "{profit_expression} {earnings_vibe}"),
            TemplateMessage("C", "[BALANCE] is the proof."),
            TemplateMessage("D", "Let's go team! AI power.")
        ]
    )

    # Archetype: BEARISH (80 msgs)
    BEAR_DUMP = ConversationTemplate(
        name="Bearish Pressure",
        sentiment="bearish",
        script=[
            TemplateMessage("X", "Ouch. [ASSET] {verb_move} {adverb_speed}."),
            TemplateMessage("Y", "{filler}. {sentiment_neg} for sure."),
            TemplateMessage("Z", "AI already hedge. [BALANCE]"),
            TemplateMessage("W", "Exactly. Better safe than sorry. [WITHDRAWAL]"),
            TemplateMessage("X", "Manual traders panicking, we are chilling."),
            TemplateMessage("Y", "Just checked the AI dashboard. [BALANCE]"),
            TemplateMessage("Z", "Price just hit a key level for [ASSET]."),
            TemplateMessage("W", "{joke}. Market is {sentiment_neg}."),
            TemplateMessage("V", "{ai_praise}. It flipped to short instantly."),
            TemplateMessage("X", "Adding margin for the next leg. [DEPOSIT]"),
            TemplateMessage("Y", "Staying liquid for now. [WITHDRAWAL]"),
            TemplateMessage("Z", "Look at this protection: [BALANCE]"),
            TemplateMessage("W", "{noun_market} is {adverb_speed} unstable."),
            TemplateMessage("V", "{earnings_vibe}. Chilling in stables now."),
            TemplateMessage("X", "Just secured some gains. [WITHDRAWAL]"),
            TemplateMessage("Y", "AI never fails. [BALANCE]"),
            TemplateMessage("Z", "{greeting}. Just woke up to this mess."),
            TemplateMessage("W", "Check the news regarding [ASSET]."),
            TemplateMessage("V", "Adding more to the AI bot. [DEPOSIT]"),
            TemplateMessage("X", "{ai_praise}. It's printing even on the dump."),
            TemplateMessage("Y", "{interjection}! [ASSET] is tanking."),
            TemplateMessage("Z", "My {noun_market} analysis says {sentiment_neg}."),
            TemplateMessage("W", "Lucky we have the AI protection. [BALANCE]"),
            TemplateMessage("V", "{earnings_vibe} {profit_expression}"),
            TemplateMessage("X", "{ai_praise}. Best hedge in history."),
            TemplateMessage("Y", "{joke}. Manual traders are fkd."),
            TemplateMessage("Z", "{market_vibe}. {filler}"),
            TemplateMessage("W", "Withdrawing some profits from short. [WITHDRAWAL]"),
            TemplateMessage("V", "{interjection}! Look at the speed."),
            TemplateMessage("X", "[BALANCE] is growing while it dumps."),
            TemplateMessage("Y", "{ai_praise}. Mister Group knows best."),
            TemplateMessage("Z", "Adding more funds to short [DEPOSIT]."),
            TemplateMessage("W", "{market_vibe} {earnings_vibe}"),
            TemplateMessage("V", "Anyone else taking [PROFIT]?"),
            TemplateMessage("A", "{greeting} fam. AI saved me again. [BALANCE]"),
            TemplateMessage("B", "{agreement}. Quant engine is smart."),
            TemplateMessage("C", "[ASSET] news is brutal."),
            TemplateMessage("D", "{filler}. {sentiment_neg} trend."),
            TemplateMessage("E", "{joke}. I'm buying a boat with short profits."),
            TemplateMessage("F", "{ai_praise}. Automation is the future."),
            TemplateMessage("X", "Retracing? No, it's a bull trap."),
            TemplateMessage("Y", "{interjection}! [BALANCE] stable."),
            TemplateMessage("Z", "{profit_expression}. Chilling."),
            TemplateMessage("W", "Look at [PROFIT] on my dashboard."),
            TemplateMessage("V", "Compounding interest is still on. [DEPOSIT]"),
            TemplateMessage("A", "{market_vibe} {earnings_vibe}"),
            TemplateMessage("B", "{ai_praise}. Logic over hype."),
            TemplateMessage("C", "Just shared result [BALANCE]"),
            TemplateMessage("D", "{joke}. See you at zero retail!"),
            TemplateMessage("E", "Safely [WITHDRAWAL] today."),
            TemplateMessage("F", "{interjection}! AI just added margin."),
            TemplateMessage("X", "[ASSET] {verb_move} {adverb_speed}."),
            TemplateMessage("Y", "{ai_praise}. Quant power."),
            TemplateMessage("Z", "{earnings_vibe}"),
            TemplateMessage("W", "Is it time to buy? No, AI says wait."),
            TemplateMessage("V", "{filler}. Market is {sentiment_neg}."),
            TemplateMessage("A", "{joke}. Manual guys crying."),
            TemplateMessage("B", "{profit_expression}"),
            TemplateMessage("C", "Look at [BALANCE] now!"),
            TemplateMessage("D", "{interjection}! Stunning protection."),
            TemplateMessage("E", "{ai_praise}. Mister is a legend."),
            TemplateMessage("F", "Always trust the system."),
            TemplateMessage("X", "{market_vibe} {filler}"),
            TemplateMessage("Y", "[WITHDRAWAL] for safety."),
            TemplateMessage("Z", "[BALANCE] still high. AI is genius."),
            TemplateMessage("W", "{joke}. I'm sleeping green."),
            TemplateMessage("V", "{ai_praise}. Best dev team."),
            TemplateMessage("A", "The {noun_market} is bleeding."),
            TemplateMessage("B", "{agreement}. But we are earning [PROFIT]."),
            TemplateMessage("C", "{earnings_vibe}"),
            TemplateMessage("D", "{profit_expression}"),
            TemplateMessage("E", "Just shared results [BALANCE]"),
            TemplateMessage("F", "Ready for the next dump."),
            TemplateMessage("X", "{ai_praise}. Quant logic wins."),
            TemplateMessage("Y", "{market_vibe}"),
            TemplateMessage("Z", "[DEPOSIT] sent to scale up."),
            TemplateMessage("W", "{interjection}! [BALANCE]"),
            TemplateMessage("V", "{joke}. RIP manual traders."),
            TemplateMessage("A", "{ai_praise}. Automation only."),
            TemplateMessage("B", "Goodnight green army.")
        ]
    )

    # Archetype: STEADY (80 msgs)
    STEADY_ACCUMULATION = ConversationTemplate(
        name="Steady AI Growth",
        sentiment="neutral",
        script=[
            TemplateMessage("A", "{greeting}. [ASSET] is quite flat today."),
            TemplateMessage("B", "{agreement}. But look at the AI stats: [PROFIT]."),
            TemplateMessage("C", "Consistency is key. {earnings_vibe} [BALANCE]."),
            TemplateMessage("D", "Just compounded my gains. [DEPOSIT]"),
            TemplateMessage("A", "{ai_praise}. No need for hype when it just works."),
            TemplateMessage("B", "{joke}. I'm barely checking the charts."),
            TemplateMessage("E", "Slow and steady wins the race. [BALANCE]"),
            TemplateMessage("F", "Did you see the latest [ASSET] report?"),
            TemplateMessage("C", "Yeah, AI already factored that in."),
            TemplateMessage("D", "Safely withdrew some for today. [WITHDRAWAL]"),
            TemplateMessage("A", "{noun_market} is in a {adverb_speed} accumulation phase."),
            TemplateMessage("B", "{filler}. I'm just holding."),
            TemplateMessage("X", "AI signal came in. Adding a bit more. [DEPOSIT]"),
            TemplateMessage("Y", "Look at this steady line: [BALANCE]"),
            TemplateMessage("Z", "{ai_praise}! Manual guys are bored, we are earning."),
            TemplateMessage("A", "{greeting}. {earnings_vibe}"),
            TemplateMessage("B", "Just the usual AI wins. [PROFIT]"),
            TemplateMessage("C", "Shared my results in the main group. [BALANCE]"),
            TemplateMessage("D", "{joke}. Compound interest is the 8th wonder."),
            TemplateMessage("E", "Getting paid daily. AI is a life changer."),
            TemplateMessage("F", "{interjection}! Another small gain. [PROFIT]"),
            TemplateMessage("X", "{market_vibe} {filler}"),
            TemplateMessage("Y", "[BALANCE] up $500 today silently."),
            TemplateMessage("Z", "{ai_praise}. Quant engine is consistent."),
            TemplateMessage("W", "{profit_expression}"),
            TemplateMessage("V", "Just added [DEPOSIT]. Scale is key."),
            TemplateMessage("A", "{earnings_vibe} {joke}"),
            TemplateMessage("B", "Who else loves passive income?"),
            TemplateMessage("C", "Me! [BALANCE] is growing daily."),
            TemplateMessage("D", "{ai_praise}. Mister Group special."),
            TemplateMessage("E", "Small moves but real money. [PROFIT]"),
            TemplateMessage("F", "Market is {sentiment_pos} but slow."),
            TemplateMessage("X", "{filler}. {noun_market} is stable."),
            TemplateMessage("Y", "Just took a partial [WITHDRAWAL]."),
            TemplateMessage("Z", "{ai_praise}. Genius logic."),
            TemplateMessage("W", "{market_vibe} {interjection}"),
            TemplateMessage("V", "[BALANCE] update fam."),
            TemplateMessage("A", "{greeting} legends. AI is on fire."),
            TemplateMessage("B", "{agreement}. {earnings_vibe}"),
            TemplateMessage("C", "[PROFIT] stacking up."),
            TemplateMessage("D", "{joke}. My boss who?"),
            TemplateMessage("E", "Best system on Telegram."),
            TemplateMessage("F", "{ai_praise}. Automation is King."),
            TemplateMessage("X", "Look at [ASSET] chart. Boring but profitable."),
            TemplateMessage("Y", "{profit_expression}"),
            TemplateMessage("Z", "Compounding now [DEPOSIT]."),
            TemplateMessage("W", "{interjection}! [BALANCE]"),
            TemplateMessage("V", "{ai_praise}. Trust the math."),
            TemplateMessage("A", "{market_vibe} {filler}"),
            TemplateMessage("B", "Just got paid again. [PROFIT]"),
            TemplateMessage("C", "{earnings_vibe}"),
            TemplateMessage("D", "[WITHDRAWAL] sent. Buying gifts!"),
            TemplateMessage("E", "{joke}. Manual trading is stress."),
            TemplateMessage("F", "{ai_praise}. AI is peace."),
            TemplateMessage("X", "{agreement}. Zero emotions here."),
            TemplateMessage("Y", "[BALANCE] looks healthy."),
            TemplateMessage("Z", "{interjection}! Look at the trend."),
            TemplateMessage("W", "[ASSET] {verb_move} {adverb_speed}."),
            TemplateMessage("V", "{ai_praise}. Quant engine logic."),
            TemplateMessage("A", "{greeting} team. {earnings_vibe}"),
            TemplateMessage("B", "Just checked balance [BALANCE]"),
            TemplateMessage("C", "{profit_expression}"),
            TemplateMessage("D", "{joke}. Retire soon."),
            TemplateMessage("E", "{ai_praise}. Mister is a genius."),
            TemplateMessage("F", "Shared results [PROFIT]"),
            TemplateMessage("X", "Market is {sentiment_neg} but we are green."),
            TemplateMessage("Y", "{filler}. AI hedges perfectly."),
            TemplateMessage("Z", "[DEPOSIT] added to pot."),
            TemplateMessage("W", "{interjection}! [BALANCE]"),
            TemplateMessage("V", "{ai_praise}. Automation wins."),
            TemplateMessage("A", "{market_vibe} {earnings_vibe}"),
            TemplateMessage("B", "Every day is payday."),
            TemplateMessage("C", "[PROFIT] is the proof."),
            TemplateMessage("D", "{joke}. RIP retail."),
            TemplateMessage("E", "{ai_praise}. Best dev ever."),
            TemplateMessage("F", "Stunning results today. [BALANCE]"),
            TemplateMessage("G", "Let's win familia."),
            TemplateMessage("H", "{earnings_vibe} {interjection}"),
            TemplateMessage("X", "[WITHDRAWAL] confirmed."),
            TemplateMessage("Y", "{ai_praise}. Quant power.")
        ]
    )

    # Archetype: VOLATILE (70 msgs)
    VOLATILE_SHAKEUP = ConversationTemplate(
        name="Volatile Protection",
        sentiment="bullish",
        script=[
            TemplateMessage("W", "Whoa! [ASSET] {verb_move} {adverb_speed}!"),
            TemplateMessage("V", "{filler}. Insane volatility."),
            TemplateMessage("A", "AI just moved to stable. [BALANCE] saved."),
            TemplateMessage("B", "{agreement}! Manual traders getting swept."),
            TemplateMessage("C", "Just checked. My trailing stop hit. [PROFIT]"),
            TemplateMessage("D", "{ai_praise}. The protection is real."),
            TemplateMessage("E", "Buying the flash crash. [DEPOSIT]"),
            TemplateMessage("W", "Is it safe? [ASSET] looks {sentiment_neg}."),
            TemplateMessage("V", "With AI? Always. Already back in green. [BALANCE]."),
            TemplateMessage("A", "{joke}. {earnings_vibe}"),
            TemplateMessage("B", "Just took a partial withdrawal. [WITHDRAWAL]"),
            TemplateMessage("C", "Look at the recovery! [ASSET] is {verb_move} back."),
            TemplateMessage("D", "{noun_market} is {adverb_speed} recovery mode."),
            TemplateMessage("E", "AI called the bottom perfectly. [BALANCE]"),
            TemplateMessage("F", "I'm adding on this {action}. [DEPOSIT]"),
            TemplateMessage("W", "{ai_praise}. It's printing even in this mess."),
            TemplateMessage("V", "{filler}. {earnings_vibe}"),
            TemplateMessage("A", "My balance is stronger than ever. [BALANCE]"),
            TemplateMessage("B", "{greeting}. Just caught the move. [PROFIT]"),
            TemplateMessage("C", "{joke}. We are getting paid while they panic."),
            TemplateMessage("D", "{interjection}! [ASSET] {verb_move} again."),
            TemplateMessage("E", "{market_vibe} {earnings_vibe}"),
            TemplateMessage("W", "{ai_praise}. Quantum logic."),
            TemplateMessage("V", "{profit_expression}"),
            TemplateMessage("A", "[BALANCE] is massive now."),
            TemplateMessage("B", "{joke}. Banks are losing control."),
            TemplateMessage("C", "{ai_praise}. Mister is elite."),
            TemplateMessage("D", "Just shared result in the group [PROFIT]"),
            TemplateMessage("E", "{filler}. {noun_market} volatility is money."),
            TemplateMessage("F", "[DEPOSIT] added on the wick."),
            TemplateMessage("G", "{interjection}! Look at that candle."),
            TemplateMessage("H", "{ai_praise}. Best automated choice ever."),
            TemplateMessage("W", "Withdrawing gains before next wave. [WITHDRAWAL]"),
            TemplateMessage("V", "{market_vibe} {earnings_vibe}"),
            TemplateMessage("A", "{joke}. I'm loving this chaos."),
            TemplateMessage("B", "Manual guys getting liquidated 😂"),
            TemplateMessage("C", "{ai_praise}. AI never sleeps."),
            TemplateMessage("D", "[PROFIT] update: +$1k!"),
            TemplateMessage("E", "{earnings_vibe} [BALANCE]"),
            TemplateMessage("F", "{interjection}! [ASSET] breaking out."),
            TemplateMessage("G", "{ai_praise}. Logic wins every time."),
            TemplateMessage("H", "Adding more to the bot [DEPOSIT]."),
            TemplateMessage("W", "{market_vibe} {filler}"),
            TemplateMessage("V", "{profit_expression}"),
            TemplateMessage("A", "[BALANCE] proof for the haters."),
            TemplateMessage("B", "{joke}. See you on the moon."),
            TemplateMessage("C", "{ai_praise}. Automation special."),
            TemplateMessage("D", "Just caught the wick! [PROFIT]"),
            TemplateMessage("E", "{earnings_vibe}"),
            TemplateMessage("F", "{interjection}! Stunning move."),
            TemplateMessage("G", "{ai_praise}. Quant engine power."),
            TemplateMessage("H", "[WITHDRAWAL] for a new car."),
            TemplateMessage("W", "Market is {sentiment_pos} for now."),
            TemplateMessage("V", "{filler}. Stay alert."),
            TemplateMessage("A", "{ai_praise}. Best system ever."),
            TemplateMessage("B", "{market_vibe} {earnings_vibe}"),
            TemplateMessage("C", "[BALANCE] up again."),
            TemplateMessage("D", "{joke}. RIP fiat."),
            TemplateMessage("E", "{ai_praise}. Mister Group for life."),
            TemplateMessage("F", "Shared results [PROFIT]"),
            TemplateMessage("W", "Ready for the next shakeup."),
            TemplateMessage("V", "{interjection}! [BALANCE]"),
            TemplateMessage("A", "{ai_praise}. Automation wins."),
            TemplateMessage("B", "Every wick is a win."),
            TemplateMessage("C", "[PROFIT] stacking up."),
            TemplateMessage("D", "{joke}. Chilling in green."),
            TemplateMessage("E", "{ai_praise}. Best dev ever."),
            TemplateMessage("F", "Stunning recovery. [BALANCE]"),
            TemplateMessage("G", "Let's win team."),
            TemplateMessage("H", "{earnings_vibe} {interjection}")
        ]
    )

    @classmethod
    def get_template(cls, sentiment: str) -> ConversationTemplate:
        import random
        if sentiment == "bearish":
            return cls.BEAR_DUMP
        elif sentiment == "bullish":
            return random.choice([cls.BULL_RUN, cls.VOLATILE_SHAKEUP])
        else:
            return cls.STEADY_ACCUMULATION

    @classmethod
    def get_template(cls, sentiment: str) -> ConversationTemplate:
        import random
        if sentiment == "bearish":
            return cls.BEAR_DUMP
        elif sentiment == "bullish":
            return random.choice([cls.BULL_RUN, cls.VOLATILE_SHAKEUP])
        else:
            return cls.STEADY_ACCUMULATION
